env:
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:astro/recommended'
  - prettier # should come last

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

root: true

rules:
  '@typescript-eslint/no-var-requires': off # give me longer to write new code before distracting me with errors
  '@typescript-eslint/triple-slash-reference': off # disable since astro automatically uses these
  dot-notation: 'error' # enforce dot notation instead of square brackets whenever possible

overrides:
  # Define the configuration for `.astro` file.
  - files: ['*.astro']
    parser: 'astro-eslint-parser'
    # parser: '@astrojs/eslint-plugin-astro/parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.astro']
    # rules:
